# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_user_likes', to='login.User'),
            preserve_default=False,
        ),
    ]
